image:
  python
test-job:
    stage: test
    script:
        - pip install flask
        - pip install coverage
        - python -m coverage run -m unittest -v tests/appTest.py
        - python -m coverage report
build-job:
  stage: build
  script:
    - echo "Olá, $GITLAB_USER_LOGIN!"]
deploy-prod-job:
  stage: deploy
  script:
      - echo "Implantando a branch $CI_COMMIT_BRANCH em produção..."
      - sleep 20
      - echo "Implantação concluída com sucesso!"
when: manual
manual_confirmation: 'Aprovar o deploy a partir da branch
$CI_COMMIT_BRANCH?'